-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 18:58:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `id` INT NOT NULL,
  `owner_fname` VARCHAR(50) NULL,
  `owner_initial` VARCHAR(50) NULL,
  `owner__lname` VARCHAR(50) NULL,
  `owner_address` VARCHAR(50) NULL,
  `owner_contact` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id` INT(5) NOT NULL,
  `supplier_loc` VARCHAR(50) NULL,
  `supplier_contact` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `customer_order` VARCHAR(25) NULL,
  `payment_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` INT(5) NOT NULL,
  `payment_type` INT NULL,
  `payment_account` FLOAT(5,2) NULL,
  `paymentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventory` (
  `id` INT(5) NOT NULL,
  `inventory_item` VARCHAR(50) NULL,
  `inventory_type` VARCHAR(50) NULL,
  `inventory_stock` INT(11) NULL,
  `inventory_sold` INT(11) NULL,
  `owner_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventory_owner1_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_owner1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`goods` (
  `id` INT(5) NOT NULL,
  `goods_quantity` INT(11) NULL,
  `goods_type` VARCHAR(50) NULL,
  `goods_date` DATE NULL,
  `DELIVERY PERSON_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goods_DELIVERY PERSON1_idx` (`DELIVERY PERSON_id` ASC) VISIBLE,
  CONSTRAINT `fk_goods_DELIVERY PERSON1`
    FOREIGN KEY (`DELIVERY PERSON_id`)
    REFERENCES `mydb`.`delivery person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id` INT(5) NOT NULL,
  `supplier_loc` VARCHAR(50) NULL,
  `supplier_contact` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`goods` (
  `id` INT(5) NOT NULL,
  `goods_quantity` INT(11) NULL,
  `goods_type` VARCHAR(50) NULL,
  `goods_date` DATE NULL,
  `DELIVERY PERSON_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goods_DELIVERY PERSON1_idx` (`DELIVERY PERSON_id` ASC) VISIBLE,
  CONSTRAINT `fk_goods_DELIVERY PERSON1`
    FOREIGN KEY (`DELIVERY PERSON_id`)
    REFERENCES `mydb`.`delivery person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery person` (
  `id` INT(5) NOT NULL,
  `delivery_person_fname` VARCHAR(50) NULL,
  `delivery_person_initial` VARCHAR(1) NULL,
  `delivery_person_lname` VARCHAR(50) NULL,
  `delivery_person_contact` INT(11) NULL,
  `delivery_person_` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`goods` (
  `id` INT(5) NOT NULL,
  `goods_quantity` INT(11) NULL,
  `goods_type` VARCHAR(50) NULL,
  `goods_date` DATE NULL,
  `DELIVERY PERSON_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goods_DELIVERY PERSON1_idx` (`DELIVERY PERSON_id` ASC) VISIBLE,
  CONSTRAINT `fk_goods_DELIVERY PERSON1`
    FOREIGN KEY (`DELIVERY PERSON_id`)
    REFERENCES `mydb`.`delivery person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery person` (
  `id` INT(5) NOT NULL,
  `delivery_person_fname` VARCHAR(50) NULL,
  `delivery_person_initial` VARCHAR(1) NULL,
  `delivery_person_lname` VARCHAR(50) NULL,
  `delivery_person_contact` INT(11) NULL,
  `delivery_person_` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `id` INT NOT NULL,
  `owner_fname` VARCHAR(50) NULL,
  `owner_initial` VARCHAR(50) NULL,
  `owner__lname` VARCHAR(50) NULL,
  `owner_address` VARCHAR(50) NULL,
  `owner_contact` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `id` INT NOT NULL,
  `owner_fname` VARCHAR(50) NULL,
  `owner_initial` VARCHAR(50) NULL,
  `owner__lname` VARCHAR(50) NULL,
  `owner_address` VARCHAR(50) NULL,
  `owner_contact` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT(5) NOT NULL,
  `owner_id(5)` VARCHAR(5) NULL,
  `employee_fname` VARCHAR(50) NULL,
  `employee_initial` VARCHAR(1) NULL,
  `employee_lname` VARCHAR(50) NULL,
  `employee_contact` INT(11) NULL,
  `employee_address` VARCHAR(50) NULL,
  `employee_shift_time` VARCHAR(45) NULL,
  `employeecol` VARCHAR(50) NULL,
  `owner_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_owner1_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_owner1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT(5) NOT NULL,
  `customer` INT(5) NULL,
  `order_amount` FLOAT(5,2) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `customer_order` VARCHAR(25) NULL,
  `payment_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `id` INT NOT NULL,
  `owner_fname` VARCHAR(50) NULL,
  `owner_initial` VARCHAR(50) NULL,
  `owner__lname` VARCHAR(50) NULL,
  `owner_address` VARCHAR(50) NULL,
  `owner_contact` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventory` (
  `id` INT(5) NOT NULL,
  `inventory_item` VARCHAR(50) NULL,
  `inventory_type` VARCHAR(50) NULL,
  `inventory_stock` INT(11) NULL,
  `inventory_sold` INT(11) NULL,
  `owner_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventory_owner1_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_owner1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner_copy2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner_copy2` (
  `id` INT NOT NULL,
  `owner_fname` VARCHAR(50) NULL,
  `owner_initial` VARCHAR(50) NULL,
  `owner__lname` VARCHAR(50) NULL,
  `owner_address` VARCHAR(50) NULL,
  `owner_contact` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financial account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financial account` (
  `id` INT NOT NULL,
  `financial_account_date` DATE NULL,
  `financial_account_gross` INT(11) NULL,
  `financial_account_purchases` INT(11) NULL,
  `financial_account_net_sale` INT(11) NULL,
  `financial_account_coh` VARCHAR(45) NULL,
  `financial_account_short` TINYINT NULL,
  `financial_account_over` TINYINT NULL,
  `owner_copy2_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_financial account_owner_copy21_idx` (`owner_copy2_id` ASC) VISIBLE,
  CONSTRAINT `fk_financial account_owner_copy21`
    FOREIGN KEY (`owner_copy2_id`)
    REFERENCES `mydb`.`owner_copy2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
